# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

<<<<<<< HEAD
    OpenAPI spec version: v1.15.6
    Generated by: https://openapi-generator.tech
=======
    OpenAPI spec version: v1.5.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
>>>>>>> release-1.0
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1_limit_range import V1LimitRange  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1LimitRange(unittest.TestCase):
    """V1LimitRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1LimitRange(self):
        """Test V1LimitRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1_limit_range.V1LimitRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
