# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

<<<<<<< HEAD
    OpenAPI spec version: v1.15.6
    Generated by: https://openapi-generator.tech
=======
    OpenAPI spec version: v1.5.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
>>>>>>> release-1.0
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1_limit_range_spec import V1LimitRangeSpec  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1LimitRangeSpec(unittest.TestCase):
    """V1LimitRangeSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1LimitRangeSpec(self):
        """Test V1LimitRangeSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1_limit_range_spec.V1LimitRangeSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
